---
title: "Data Analysis Project"
author: "Zach Sturgill"
date: "2026-04-27"
output: html_notebook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

In this project, we are analyzing the women's college basketball dataset.

## Load libraries

Loading required libraries for this analysis.

```{r echo=FALSE, message=FALSE}
library(tidyverse)
library(lubridate)
library(janitor)
```

## Load and Cleaning Data

In this section, describe the source of the data, write a basic data dictionary for data you are working with, and discuss any caveats or issues you discovered working with this data.

```{r}
wbb_2020_roster <- read_csv("womens-college-basketball-main/wbb_rosters_2020_21.csv") |> clean_names()
wbb_2021_roster <- read_csv("womens-college-basketball-main/wbb_rosters_2021_22.csv") |> clean_names()
wbb_2022_roster <- read_csv("womens-college-basketball-main/wbb_rosters_2022_23.csv") |> clean_names()
wbb_2023_roster <- read_csv("womens-college-basketball-main/wbb_rosters_2023_24.csv") |> clean_names()
wbb_2024_roster <- read_csv("womens-college-basketball-main/wbb_rosters_2024_25.csv") |> clean_names()
wbb_2025_roster <- read_csv("womens-college-basketball-main/wbb_rosters_2025_26.csv") |> clean_names()
coaching_history <- read_csv("womens-college-basketball-main/coaches/coaches_with_history.csv") |> clean_names()
teams <- read_csv("womens-college-basketball-main/teams.csv") |> clean_names()
```
